create database IF NOT EXISTS nanban;
use nanban;
create table IF NOT EXISTS Register(name varchar(255) primary key,password varchar(255) NOT NULL);
insert into Register values('sanmugapriya','sanmugapriya');
insert into Register values('aarthi','aarthi');
insert into Register values('aarthy','aarthy');
insert into Register values('aishwarya','aishwarya');
insert into Register values('akilan','akilan');
insert into Register values('akshaya','akshaya');
insert into Register values('anandhan','anandhan');
insert into Register values('anusowbarani','anusowbarani');
insert into Register values('aravind ayyadurai','aravind ayyadurai');
insert into Register values('aravinda','aravinda');
insert into Register values('aravindpr','aravindpr');
insert into Register values('aravindh surya','aravindh surya');
insert into Register values('aravindkumar','aravindkumar');
insert into Register values('archana','archana');
insert into Register values('arunkumar','arunkumar');
insert into Register values('arunpriya','arunpriya');
insert into Register values('azma','azma');
insert into Register values('bala adhethan','bala adhethan');
insert into Register values('balaji','balaji');
insert into Register values('charulatha','charulatha');
insert into Register values('chandeesh babu','chandeesh babu');
insert into Register values('dharaneshwar','dharaneshwar');
insert into Register values('dhivya','dhivya');
insert into Register values('dineshkumar','dineshkumar');
insert into Register values('divya krishnaveni','divya krishnaveni');
insert into Register values('divyas','divyas');
insert into Register values('divyam','divyam');
insert into Register values('elizabeth','elizabeth');
insert into Register values('enimai','enimai');
insert into Register values('gokulan','gokulan');
insert into Register values('gokulavani','gokulavani');
insert into Register values('gowtham swaminathan','gowtham swaminathan');
insert into Register values('hari haran','hari haran');
insert into Register values('harine rajashree','harine rajashree');
insert into Register values('haseena banu','haseena banu');
insert into Register values('hasika','hasika');
insert into Register values('havishmathy','havishmathy');
insert into Register values('indhumathi','indhumathi');
insert into Register values('jaganathan','jaganathan');
insert into Register values('jenson','jenson');
insert into Register values('jones','jones');
insert into Register values('joshi angel saranya','joshi angel saranya');
insert into Register values('kavi priya','kavi priya');
insert into Register values('kavya','kavya');
insert into Register values('keerthika','keerthika');
insert into Register values('kesava rajkumar','kesava rajkumar');
insert into Register values('kiran raj','kiran raj');
insert into Register values('kiruthika','kiruthika');
insert into Register values('kishore','kishore');
insert into Register values('krishnapriya','krishnapriya');
insert into Register values('mahalingam','mahalingam');
insert into Register values('mangala ishwarya','mangala ishwarya');
insert into Register values('manikandan','manikandan');
insert into Register values('manoj kumar','manoj kumar');
insert into Register values('manoj','manoj');
insert into Register values('mariselvam','mariselvam');
insert into Register values('meenakshi','meenakshi');
insert into Register values('meenalakshmi','meenalakshmi');
insert into Register values('meyyappan','meyyappan');
insert into Register values('mohamed hushain','mohamed hushain');
insert into Register values('mohana priya','mohana priya');
insert into Register values('muthu alagappan','muthu alagappan');
insert into Register values('nagasurya','nagasurya');
insert into Register values('nagavalli','nagavalli');
insert into Register values('naveen kumars','naveen kumars');
insert into Register values('naveen kumarr','naveen kumarr');
insert into Register values('naveen','naveen');
insert into Register values('nikisha devi','nikisha devi');
insert into Register values('nisha','nisha');
insert into Register values('niveditha','niveditha');
insert into Register values('nivetha devi','nivetha devi');
insert into Register values('padma nivashini','padma nivashini');
insert into Register values('pattulakshmi','pattulakshmi');
insert into Register values('pavithra','pavithra');
insert into Register values('pragadeesh','pragadeesh');
insert into Register values('prathiba','prathiba');
insert into Register values('prathusha','prathusha');
insert into Register values('prayaksitha','prayaksitha');
insert into Register values('pressannasri','pressannasri');
insert into Register values('puratchi','puratchi');
insert into Register values('puviyarasu','puviyarasu');
insert into Register values('rajeswaran','rajeswaran');
insert into Register values('ram shankaranath','ram shankaranath');
insert into Register values('ramyaks','ramyaks');
insert into Register values('ramyas','ramyas');
insert into Register values('ramya,s','ramya,s');
insert into Register values('revathi','revathi');
insert into Register values('sangavi','sangavi');
insert into Register values('sapna meenu','sapna meenu');
insert into Register values('selvaganesh','selvaganesh');
insert into Register values('senthil','senthil');
insert into Register values('sharadha','sharadha');
insert into Register values('sharifa','sharifa');
insert into Register values('sharmilee','sharmilee');
insert into Register values('shenbagalakshmi','shenbagalakshmi');
insert into Register values('sheva arthi','sheva arthi');
insert into Register values('shiva shankari','shiva shankari');
insert into Register values('shivasurya','shivasurya');
insert into Register values('siddarth','siddarth');
insert into Register values('sneha','sneha');
insert into Register values('sowmeya','sowmeya');
insert into Register values('srinivetha','srinivetha');
insert into Register values('sriramamoorthy','sriramamoorthy');
insert into Register values('sujitha','sujitha');
insert into Register values('surya','surya');
insert into Register values('swarna lakshmi','swarna lakshmi');
insert into Register values('tamil selvan','tamil selvan');
insert into Register values('thanusri','thanusri');
insert into Register values('udhaya suriyan','udhaya suriyan');
insert into Register values('vaanmathi','vaanmathi');
insert into Register values('varshini','varshini');
insert into Register values('venkatraman','venkatraman');
insert into Register values('vignesh','vignesh');
insert into Register values('vigneswari','vigneswari');
insert into Register values('vimal kanna','vimal kanna');
insert into Register values('ajeeth kumar','ajeeth kumar');
insert into Register values('aswini','aswini');
insert into Register values('balammal','balammal');
insert into Register values('chandru','chandru');
insert into Register values('dharsini','dharsini');
insert into Register values('karthick','karthick');
insert into Register values('karthikkumar','karthikkumar');
insert into Register values('kumaresan','kumaresan');
insert into Register values('maheswari','maheswari');
insert into Register values('mathi sundar','mathi sundar');
insert into Register values('nandhini','nandhini');
insert into Register values('radha','radha');
insert into Register values('ramkumar','ramkumar');
insert into Register values('sanjay','sanjay');
insert into Register values('satheesh kumar','satheesh kumar');
insert into Register values('seetharaman','seetharaman');
insert into Register values('sheik dawood','sheik dawood');
insert into Register values('sridevi','sridevi');
insert into Register values('srinath','srinath');
insert into Register values('syed abuthahir','syed abuthahir');
insert into Register values('udhaya kumar','udhaya kumar');
insert into Register values('vasugi','vasugi');
insert into Register values('yazhini priya','yazhini priya');
